import { useCallback, useEffect, useState } from 'react';
import { Alert as RNAlert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { apiRequest } from '../../src/services/api';

type PriceAlert={id:number;symbol:string;target_price:number;condition:'above'|'below';is_active:boolean;created_at:string};

export default function AlertsScreen(){
  const [items,setItems]=useState<PriceAlert[]>([]); const [symbol,setSymbol]=useState(''); const [target,setTarget]=useState(''); const [condition,setCondition]=useState<'above'|'below'>('above'); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setItems(await apiRequest<PriceAlert[]>('/api/alerts'));}catch{}finally{setLoading(false);}},[]); useEffect(()=>{load();},[load]);
  const save=async()=>{if(!symbol.trim()||!Number(target))return;try{await apiRequest('/api/alerts',{method:'POST',body:JSON.stringify({symbol:symbol.trim().toUpperCase(),target_price:Number(target),condition})});setTarget('');await load();}catch(e){RNAlert.alert('Error',e instanceof Error?e.message:'Unable to save.');}};
  const remove=async(id:number)=>{try{await apiRequest(`/api/alerts/${id}`,{method:'DELETE'});await load();}catch{}};
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#60a5fa"/>}><Text style={s.kicker}>REMEMBER LEVELS</Text><Text style={s.title}>Alerts</Text><Text style={s.sub}>Mark a price level so you do not need to keep watching the screen.</Text><TextInput style={s.input} value={symbol} onChangeText={setSymbol} placeholder="Symbol" placeholderTextColor="#64748b"/><TextInput style={s.input} value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="Target price" placeholderTextColor="#64748b"/><View style={s.row}><TouchableOpacity style={[s.choice,condition==='above'&&s.active]} onPress={()=>setCondition('above')}><Text style={s.btn}>Above</Text></TouchableOpacity><TouchableOpacity style={[s.choice,condition==='below'&&s.active]} onPress={()=>setCondition('below')}><Text style={s.btn}>Below</Text></TouchableOpacity></View><TouchableOpacity style={s.primary} onPress={save}><Text style={s.btn}>Create alert</Text></TouchableOpacity><Text style={s.heading}>Saved alerts</Text>{items.map(x=><View key={x.id} style={s.card}><View><Text style={s.symbol}>{x.symbol}</Text><Text style={s.body}>{x.condition.toUpperCase()} ₹{x.target_price.toLocaleString('en-IN')}</Text></View><TouchableOpacity onPress={()=>remove(x.id)}><Text style={s.remove}>Remove</Text></TouchableOpacity></View>)}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0f172a'},content:{padding:24},kicker:{color:'#60a5fa',fontSize:11,fontWeight:'900'},title:{color:'#f8fafc',fontSize:30,fontWeight:'900'},sub:{color:'#94a3b8',marginVertical:12},input:{backgroundColor:'#111827',borderWidth:1,borderColor:'#334155',borderRadius:10,padding:14,color:'#f8fafc',marginBottom:10},row:{flexDirection:'row',gap:10,marginBottom:10},choice:{flex:1,backgroundColor:'#1e293b',padding:12,borderRadius:10,alignItems:'center'},active:{backgroundColor:'#1d4ed8'},primary:{backgroundColor:'#2563eb',padding:14,borderRadius:10,alignItems:'center'},btn:{color:'#fff',fontWeight:'800'},heading:{color:'#f8fafc',fontSize:18,fontWeight:'800',marginVertical:18},card:{backgroundColor:'#111827',borderWidth:1,borderColor:'#334155',borderRadius:12,padding:16,marginBottom:10,flexDirection:'row',justifyContent:'space-between'},symbol:{color:'#60a5fa',fontWeight:'900'},body:{color:'#cbd5e1',marginTop:4},remove:{color:'#f87171',fontWeight:'700'}});
