import { useCallback, useEffect, useState } from 'react';
import { Alert, RefreshControl, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { apiRequest } from '../../src/services/api';

type Entry={id:number;symbol:string;title:string;note:string;confidence:number|null;created_at:string};

export default function JournalScreen(){
  const [entries,setEntries]=useState<Entry[]>([]); const [symbol,setSymbol]=useState(''); const [title,setTitle]=useState(''); const [note,setNote]=useState(''); const [confidence,setConfidence]=useState('5'); const [loading,setLoading]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{setEntries(await apiRequest<Entry[]>('/api/journal'));}catch{}finally{setLoading(false);}},[]); useEffect(()=>{load();},[load]);
  const save=async()=>{if(!symbol.trim()||!title.trim()||!note.trim())return;try{await apiRequest('/api/journal',{method:'POST',body:JSON.stringify({symbol:symbol.trim().toUpperCase(),title:title.trim(),note:note.trim(),confidence:Number(confidence)||5,mistake:false})});setTitle('');setNote('');await load();}catch(e){Alert.alert('Error',e instanceof Error?e.message:'Unable to save.');}};
  return <ScrollView style={s.page} contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={load} tintColor="#60a5fa"/>}><Text style={s.kicker}>DECIDE</Text><Text style={s.title}>Journal</Text><Text style={s.sub}>Record the decision and the reason before the outcome is known.</Text><TextInput style={s.input} value={symbol} onChangeText={setSymbol} placeholder="Symbol" placeholderTextColor="#64748b"/><TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Decision / idea" placeholderTextColor="#64748b"/><TextInput style={[s.input,s.note]} value={note} onChangeText={setNote} multiline placeholder="Why? What are you expecting?" placeholderTextColor="#64748b"/><TextInput style={s.input} value={confidence} onChangeText={setConfidence} keyboardType="number-pad" placeholder="Confidence 1–10" placeholderTextColor="#64748b"/><TouchableOpacity style={s.primary} onPress={save}><Text style={s.btn}>Save decision</Text></TouchableOpacity><Text style={s.heading}>Past decisions</Text>{entries.map(x=><View key={x.id} style={s.card}><Text style={s.symbol}>{x.symbol} · {x.title}</Text><Text style={s.body}>{x.note}</Text><Text style={s.meta}>Confidence {x.confidence??'—'} · {new Date(x.created_at).toLocaleString()}</Text></View>)}</ScrollView>;
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#0f172a'},content:{padding:24},kicker:{color:'#60a5fa',fontSize:11,fontWeight:'900'},title:{color:'#f8fafc',fontSize:30,fontWeight:'900'},sub:{color:'#94a3b8',marginVertical:12},input:{backgroundColor:'#111827',borderWidth:1,borderColor:'#334155',borderRadius:10,padding:14,color:'#f8fafc',marginBottom:10},note:{minHeight:100,textAlignVertical:'top'},primary:{backgroundColor:'#2563eb',padding:14,borderRadius:10,alignItems:'center'},btn:{color:'#fff',fontWeight:'800'},heading:{color:'#f8fafc',fontSize:18,fontWeight:'800',marginVertical:18},card:{backgroundColor:'#111827',borderWidth:1,borderColor:'#334155',borderRadius:12,padding:16,marginBottom:10},symbol:{color:'#60a5fa',fontWeight:'800'},body:{color:'#cbd5e1',marginTop:6},meta:{color:'#64748b',fontSize:11,marginTop:10}});
