import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { theme } from '../../src/shared/theme/tokens';
import { apiRequest } from '../../src/services/api';
import { AssetSearch, type Asset } from '../../src/features/market/AssetSearch';
import { Page, PageIntro, PrimaryAction, SectionHeading, formatPrice } from '../../src/shared/ui/NotebookUI';
import { dayAfter } from '../../src/features/journal/reviewDates';

type WatchItem={id:number;symbol:string;name:string|null;asset_type:'stock'|'crypto';backend_id:string|null};
type PriceQuote={price:number;currency:string;source:string};
type Expectation='bullish'|'bearish'|'neutral';

export default function CaptureScreen(){
  const [selected,setSelected]=useState<Asset|null>(null);const [quote,setQuote]=useState<PriceQuote|null>(null);const [thought,setThought]=useState('');const [expectation,setExpectation]=useState<Expectation>('neutral');const [reviewDue,setReviewDue]=useState(dayAfter(14));const [watchlist,setWatchlist]=useState<WatchItem[]>([]);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const savingRef=useRef(false);const [message,setMessage]=useState('');const [showContext,setShowContext]=useState(false);const [alertPrice,setAlertPrice]=useState('');const [condition,setCondition]=useState<'above'|'below'>('above');
  const loadWatchlist=useCallback(async()=>{setLoading(true);try{setWatchlist(await apiRequest<WatchItem[]>('/api/watchlist'));}catch(e){setMessage(e instanceof Error?e.message:'Unable to load watchlist.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void loadWatchlist();},[loadWatchlist]);
  const selectAsset=async(asset:Asset)=>{setSelected(asset);setQuote(null);setMessage('');setAlertPrice('');try{const q=await apiRequest<PriceQuote>(`/api/assets/price?asset_type=${asset.asset_type}&backend_id=${encodeURIComponent(asset.backend_id)}`);setQuote(q);setAlertPrice(String(q.price));}catch(e){setMessage(e instanceof Error?e.message:'Live price is unavailable. Your thought can still be saved.');}};
  const selectedInWatchlist=useMemo(()=>selected?watchlist.some(x=>x.symbol===selected.symbol&&x.asset_type===selected.asset_type):false,[selected,watchlist]);
  const saveThought=async()=>{if(savingRef.current||!selected||!thought.trim())return;savingRef.current=true;setSaving(true);setMessage('');try{await apiRequest('/api/journal',{method:'POST',body:JSON.stringify({symbol:selected.symbol,asset_name:selected.name,asset_type:selected.asset_type,backend_id:selected.backend_id,exchange:selected.exchange??null,title:thought.trim().slice(0,80),note:thought.trim(),confidence:5,mistake:false,entry_type:'observation',decision_action:null,expectation,invalidation:null,review_due_on:reviewDue||null})});setThought('');setMessage('Thought saved. It will return when it is time to review.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save. Your draft is still here.');}finally{savingRef.current=false;setSaving(false);}};
  const addWatchlist=async()=>{if(!selected||selectedInWatchlist)return;try{await apiRequest('/api/watchlist',{method:'POST',body:JSON.stringify({symbol:selected.symbol,name:selected.name,asset_type:selected.asset_type,backend_id:selected.backend_id})});await loadWatchlist();setMessage('Asset added to your watchlist.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to update watchlist.');}};
  const saveSnapshot=async()=>{if(!selected)return;try{await apiRequest('/api/snapshots',{method:'POST',body:JSON.stringify({symbol:selected.symbol,asset_name:selected.name,asset_type:selected.asset_type,backend_id:selected.backend_id,price:quote?.price??null,note:thought.trim()||null,market_payload:{currency:quote?.currency??null,source:quote?.source??null,exchange:selected.exchange??null}})});setMessage('Market context captured.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to capture context.');}};
  const createAlert=async()=>{if(!selected)return;const target=Number(alertPrice);if(!Number.isFinite(target)||target<=0){setMessage('Enter a valid remembered price level.');return;}try{await apiRequest('/api/alerts',{method:'POST',body:JSON.stringify({symbol:selected.symbol,target_price:target,condition,asset_type:selected.asset_type,backend_id:selected.backend_id,currency:quote?.currency??null})});setMessage(`Price level remembered for ${selected.symbol}.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to remember price level.');}};
  return <ScrollView style={s.screen} contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={loading} onRefresh={loadWatchlist} tintColor={theme.colors.accent}/>}><Page>
    <PageIntro eyebrow="Capture" title="What are you thinking?" subtitle="One thought now. A clearer lesson later."/>
    <AssetSearch selected={selected} onSelect={asset=>void selectAsset(asset)} onClearSelection={()=>{setSelected(null);setQuote(null);}} placeholder="Choose an asset"/>
    {selected?<View style={s.asset}><View><Text style={s.symbol}>{selected.symbol}</Text><Text style={s.assetName}>{selected.name} · {selected.exchange||selected.asset_type}</Text></View><View style={s.priceSide}><Text style={s.price}>{quote?formatPrice(quote.price,quote.currency):'—'}</Text><Text style={s.marketMeta}>{quote?'Current context · may be delayed':'Price unavailable'}</Text></View></View>:null}
    <TextInput accessibilityLabel="Your market thought" value={thought} onChangeText={setThought} multiline maxLength={5000} style={s.thoughtInput} placeholder="I think…" placeholderTextColor={theme.colors.textDim}/>
    <Text style={s.label}>Expectation</Text><View style={s.options}>{(['bullish','bearish','neutral'] as Expectation[]).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:expectation===value}} onPress={()=>setExpectation(value)} style={[s.option,expectation===value&&s.optionActive]}><Text style={[s.optionText,expectation===value&&s.optionTextActive]}>{expectation===value?'●':'○'} {value[0].toUpperCase()+value.slice(1)}</Text></Pressable>)}</View>
    <Text style={s.label}>Bring this back</Text><View style={s.options}>{[[7,'1 week'],[14,'2 weeks'],[30,'1 month'],[90,'3 months']].map(([days,label])=><Pressable key={String(days)} onPress={()=>setReviewDue(dayAfter(Number(days)))} style={[s.option,reviewDue===dayAfter(Number(days))&&s.optionActive]}><Text style={[s.optionText,reviewDue===dayAfter(Number(days))&&s.optionTextActive]}>{label}</Text></Pressable>)}</View>
    <View style={s.save}><PrimaryAction label={saving?'Saving…':'Save thought'} disabled={!selected||!thought.trim()||saving} onPress={()=>void saveThought()}/></View>
    {message?<Text accessibilityRole="alert" style={s.message}>{message}</Text>:null}
    <Pressable onPress={()=>setShowContext(value=>!value)} style={s.contextToggle}><Text style={s.contextToggleText}>{showContext?'− Hide market tools':'+ Add market context'}</Text><Text style={s.contextHint}>Optional</Text></Pressable>
    {showContext?<View style={s.context}>
      <SectionHeading title="Market context" detail="Supporting details, not the memory"/>
      <View style={s.toolRow}><Pressable disabled={!selected||selectedInWatchlist} onPress={()=>void addWatchlist()} style={[s.secondary,(!selected||selectedInWatchlist)&&s.disabled]}><Text style={s.secondaryText}>{selectedInWatchlist?'✓ In watchlist':'Add to watchlist'}</Text></Pressable><Pressable disabled={!selected} onPress={()=>void saveSnapshot()} style={[s.secondary,!selected&&s.disabled]}><Text style={s.secondaryText}>Capture price snapshot</Text></Pressable></View>
      <Text style={s.label}>Remember a price level</Text><TextInput value={alertPrice} onChangeText={setAlertPrice} keyboardType="decimal-pad" placeholder="Target price" placeholderTextColor={theme.colors.textDim} style={s.smallInput}/><View style={s.toolRow}>{(['above','below'] as const).map(value=><Pressable key={value} onPress={()=>setCondition(value)} style={[s.secondary,condition===value&&s.secondarySelected]}><Text style={s.secondaryText}>{value}</Text></Pressable>)}<Pressable disabled={!selected} onPress={()=>void createAlert()} style={[s.secondary,!selected&&s.disabled]}><Text style={s.secondaryText}>Remember level</Text></Pressable></View>
    </View>:null}
  </Page></ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.colors.bg},scroll:{minHeight:'100%'},asset:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:theme.space.md,borderBottomWidth:1,borderBottomColor:theme.colors.borderSubtle,paddingVertical:theme.space.lg},symbol:{...theme.type.asset,color:theme.colors.text},assetName:{...theme.type.caption,color:theme.colors.textMuted,marginTop:2},priceSide:{alignItems:'flex-end'},price:{...theme.type.marketValue,color:theme.colors.text},marketMeta:{...theme.type.metadata,color:theme.colors.textDim,marginTop:2},thoughtInput:{minHeight:168,color:theme.colors.text,fontSize:20,lineHeight:30,textAlignVertical:'top',paddingVertical:theme.space.xl,borderBottomWidth:1,borderBottomColor:theme.colors.border,outlineStyle:'none' as never},label:{...theme.type.metadata,color:theme.colors.textDim,textTransform:'uppercase',marginTop:theme.space.lg,marginBottom:theme.space.xs},options:{flexDirection:'row',flexWrap:'wrap',gap:theme.space.xs},option:{minHeight:42,justifyContent:'center',paddingHorizontal:theme.space.sm,borderWidth:1,borderColor:theme.colors.borderSubtle,borderRadius:theme.radius.pill},optionActive:{borderColor:theme.colors.accent,backgroundColor:theme.colors.accentSoft},optionText:{...theme.type.caption,color:theme.colors.textMuted},optionTextActive:{color:theme.colors.text},save:{marginTop:theme.space.xl,alignSelf:'flex-start',minWidth:160},message:{...theme.type.caption,color:theme.colors.textSecondary,marginTop:theme.space.sm},contextToggle:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',minHeight:52,borderTopWidth:1,borderTopColor:theme.colors.borderSubtle,marginTop:theme.space.xl},contextToggleText:{...theme.type.caption,color:theme.colors.textSecondary},contextHint:{...theme.type.metadata,color:theme.colors.textDim},context:{paddingBottom:theme.space.lg},toolRow:{flexDirection:'row',flexWrap:'wrap',gap:theme.space.xs},secondary:{minHeight:42,justifyContent:'center',paddingHorizontal:theme.space.sm,borderWidth:1,borderColor:theme.colors.border,borderRadius:theme.radius.sm},secondarySelected:{backgroundColor:theme.colors.accentSoft,borderColor:theme.colors.accent},secondaryText:{...theme.type.caption,color:theme.colors.textSecondary},smallInput:{minHeight:46,color:theme.colors.text,backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.border,borderRadius:theme.radius.sm,paddingHorizontal:theme.space.sm,marginBottom:theme.space.xs},disabled:{opacity:.4}});
