import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiRequest } from '../../services/api';
import { theme } from '../../shared/theme/tokens';
import { EmptyState, Page, PageIntro, SectionHeading } from '../../shared/ui/NotebookUI';

type Entry={id:number;confidence:number|null;reviewed_at?:string|null;review_outcome?:'yes'|'partially'|'no'|null;lesson?:string|null};
type Reflection={answer:string;provider:string;model:string;source_entry_ids:number[]};
const STARTERS=['Which assumptions in my recent thoughts need stronger evidence?','What pattern appears in my completed reviews?','Where has my confidence been higher than my evidence?'];

export function ReflectScreen(){
  const [entries,setEntries]=useState<Entry[]>([]);const [question,setQuestion]=useState(STARTERS[0]);const [result,setResult]=useState<Reflection|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  useFocusEffect(useCallback(()=>{let active=true;apiRequest<Entry[]>('/api/journal?limit=100').then(rows=>{if(active)setEntries(rows);}).catch(()=>{if(active)setEntries([]);});return()=>{active=false;};},[]));
  const stats=useMemo(()=>({total:entries.length,reviewed:entries.filter(x=>x.reviewed_at).length,partial:entries.filter(x=>x.review_outcome==='partially').length,active:entries.filter(x=>!x.reviewed_at).length}),[entries]);
  const recentLessons=useMemo(()=>entries.filter(x=>x.lesson).slice(0,3),[entries]);
  async function reflect(){const clean=question.trim();if(clean.length<3||loading)return;setLoading(true);setError('');setResult(null);try{setResult(await apiRequest<Reflection>('/api/assistant/ask',{method:'POST',body:JSON.stringify({question:clean})}));}catch(e){setError(e instanceof Error?e.message:'Reflection is unavailable right now.');}finally{setLoading(false);}}
  return <ScrollView style={s.screen} contentContainerStyle={s.scroll} keyboardShouldPersistTaps="handled"><Page>
    <PageIntro eyebrow="Reflect" title="Notice how you think." subtitle="Patterns from your own memories—not predictions, signals, or advice."/>
    {!entries.length?<EmptyState title="Reflection needs memories." body="Record a few thoughts, return to review them, and this space will help you notice what repeats."/>:<>
      <SectionHeading title="Your recent thinking"/><View style={s.stats}><Stat value={stats.total} label="memories"/><Stat value={stats.reviewed} label="reviewed"/><Stat value={stats.partial} label="partially held"/><Stat value={stats.active} label="still active"/></View>
      <SectionHeading title="Lessons you preserved" detail="Most recent"/>{recentLessons.length?recentLessons.map(entry=><View key={entry.id} style={s.lesson}><Text style={s.lessonMark}>↳</Text><Text style={s.lessonText}>{entry.lesson}</Text></View>):<Text style={s.body}>Completed reviews will collect your lessons here.</Text>}
      <SectionHeading title="Ask your notebook" detail="Uses only your journal"/>
      <Text style={s.body}>Use this after reviewing several memories. It looks for reasoning patterns in your own words.</Text>
      <View style={s.prompt}><TextInput accessibilityLabel="Reflection question" multiline maxLength={2000} value={question} onChangeText={setQuestion} style={s.input} placeholderTextColor={theme.colors.textDim}/><Pressable accessibilityRole="button" disabled={loading||question.trim().length<3} onPress={()=>void reflect()} style={[s.button,loading&&s.disabled]}>{loading?<ActivityIndicator color="#07111F"/>:<Text style={s.buttonText}>Reflect on my memories</Text>}</Pressable></View>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.starters}>{STARTERS.map(item=><Pressable key={item} onPress={()=>setQuestion(item)} style={s.chip}><Text style={s.chipText}>{item}</Text></Pressable>)}</ScrollView>
      {error?<Text accessibilityRole="alert" style={s.error}>{error}</Text>:null}{result?<View style={s.result}><Text style={s.resultTitle}>Reflection</Text><Text selectable style={s.answer}>{result.answer}</Text><Text style={s.meta}>{result.source_entry_ids.length?`Based on memories ${result.source_entry_ids.join(', ')}`:'No matching journal evidence found.'}</Text></View>:null}
    </>}
  </Page></ScrollView>;
}
function Stat({value,label}:{value:number;label:string}){return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.meta}>{label}</Text></View>;}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.colors.bg},scroll:{minHeight:'100%'},stats:{flexDirection:'row',flexWrap:'wrap',borderTopWidth:1,borderBottomWidth:1,borderColor:theme.colors.borderSubtle},stat:{flexGrow:1,flexBasis:130,paddingVertical:theme.space.lg},statValue:{fontSize:26,lineHeight:32,fontWeight:'500',color:theme.colors.text},meta:{...theme.type.metadata,color:theme.colors.textDim,marginTop:3},lesson:{flexDirection:'row',gap:theme.space.sm,borderBottomWidth:1,borderBottomColor:theme.colors.borderSubtle,paddingVertical:theme.space.md},lessonMark:{color:theme.colors.review,fontSize:18},lessonText:{...theme.type.body,color:theme.colors.text,flex:1},body:{...theme.type.body,color:theme.colors.textMuted},prompt:{backgroundColor:theme.colors.surface,borderWidth:1,borderColor:theme.colors.borderSubtle,borderRadius:theme.radius.md,padding:theme.space.md,marginTop:theme.space.sm},input:{minHeight:112,color:theme.colors.text,fontSize:16,lineHeight:24,textAlignVertical:'top'},button:{alignSelf:'flex-start',minHeight:44,justifyContent:'center',backgroundColor:theme.colors.accent,borderRadius:theme.radius.sm,paddingHorizontal:theme.space.md},buttonText:{color:'#07111F',fontWeight:'600'},disabled:{opacity:.5},starters:{gap:theme.space.xs,paddingVertical:theme.space.sm},chip:{maxWidth:260,minHeight:44,justifyContent:'center',paddingHorizontal:theme.space.sm,borderRadius:theme.radius.sm,borderWidth:1,borderColor:theme.colors.borderSubtle},chipText:{...theme.type.caption,color:theme.colors.textMuted},error:{...theme.type.caption,color:theme.colors.negative},result:{borderTopWidth:1,borderTopColor:theme.colors.borderSubtle,paddingTop:theme.space.lg,marginTop:theme.space.lg},resultTitle:{...theme.type.sectionTitle,color:theme.colors.text},answer:{...theme.type.body,color:theme.colors.text,marginTop:theme.space.sm}});
