import { useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { apiRequest } from '../../services/api';
import { theme } from '../../shared/theme/tokens';

type Reflection = {
  answer: string;
  provider: string;
  model: string;
  source_entry_ids: number[];
};

const STARTERS = [
  'Which assumptions in my recent thoughts need stronger evidence?',
  'What pattern appears in my completed reviews?',
  'Where has my confidence been higher than my evidence?',
];

export function ReflectScreen() {
  const [question, setQuestion] = useState(STARTERS[0]);
  const [result, setResult] = useState<Reflection | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  async function reflect() {
    const clean = question.trim();
    if (clean.length < 3 || loading) return;
    setLoading(true); setError(''); setResult(null);
    try {
      setResult(await apiRequest<Reflection>('/api/assistant/ask', {
        method: 'POST', body: JSON.stringify({ question: clean }),
      }));
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Reflection is unavailable right now.');
    } finally { setLoading(false); }
  }

  return <ScrollView style={s.page} contentContainerStyle={s.content} keyboardShouldPersistTaps="handled">
    <Text style={s.eyebrow}>JOURNAL REFLECTION</Text>
    <Text style={s.title}>Challenge your reasoning.</Text>
    <Text style={s.body}>The assistant uses only your saved journal entries. It cannot predict returns or tell you what to buy.</Text>
    <View style={s.card}>
      <Text style={s.label}>What do you want to examine?</Text>
      <TextInput accessibilityLabel="Reflection question" multiline maxLength={2000} value={question} onChangeText={setQuestion} style={s.input} placeholderTextColor={theme.colors.textMuted} />
      <Pressable accessibilityRole="button" disabled={loading || question.trim().length < 3} onPress={reflect} style={[s.button, loading && s.disabled]}>
        {loading ? <ActivityIndicator color="#fff" /> : <Text style={s.buttonText}>Reflect on my journal</Text>}
      </Pressable>
    </View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.starters}>
      {STARTERS.map(item => <Pressable key={item} onPress={() => setQuestion(item)} style={s.chip}><Text style={s.chipText}>{item}</Text></Pressable>)}
    </ScrollView>
    {!!error && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}
    {result && <View style={s.card}>
      <Text style={s.heading}>Reflection</Text>
      <Text selectable style={s.answer}>{result.answer}</Text>
      <Text style={s.meta}>{result.source_entry_ids.length ? `Based on journal entries: ${result.source_entry_ids.join(', ')}` : 'No matching journal evidence found.'}</Text>
      <Text style={s.meta}>Generated by {result.provider} · {result.model}</Text>
    </View>}
  </ScrollView>;
}

const s = StyleSheet.create({
  page:{flex:1,backgroundColor:theme.colors.bg},content:{padding:16,width:'100%',maxWidth:760,alignSelf:'center',gap:14},
  eyebrow:{color:theme.colors.primary,fontSize:12,fontWeight:'700'},title:{color:theme.colors.text,fontSize:28,fontWeight:'700'},
  body:{color:theme.colors.textMuted,fontSize:16,lineHeight:24},card:{padding:16,borderRadius:12,backgroundColor:theme.colors.panel,borderColor:theme.colors.border,borderWidth:1,gap:12},
  label:{color:theme.colors.text,fontSize:16,fontWeight:'700'},input:{minHeight:120,color:theme.colors.text,borderColor:theme.colors.border,borderWidth:1,borderRadius:10,padding:12,textAlignVertical:'top',fontSize:16},
  button:{minHeight:48,backgroundColor:theme.colors.primaryStrong,borderRadius:10,alignItems:'center',justifyContent:'center',paddingHorizontal:16},disabled:{opacity:.55},buttonText:{color:'#fff',fontWeight:'700'},
  starters:{gap:8},chip:{maxWidth:260,padding:12,borderRadius:10,borderWidth:1,borderColor:theme.colors.border,backgroundColor:theme.colors.panel},chipText:{color:theme.colors.primary,lineHeight:20},
  heading:{color:theme.colors.text,fontSize:18,fontWeight:'700'},answer:{color:theme.colors.text,fontSize:16,lineHeight:25},meta:{color:theme.colors.textMuted,fontSize:12},error:{color:'#dc2626',fontSize:15},
});
