-- Market Memory v1 core schema

create table if not exists public.market_observations (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  asset_name text,
  asset_type text not null check (asset_type in ('crypto','stock')),
  backend_id text,
  observation text not null,
  price numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.market_snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  asset_name text,
  asset_type text not null check (asset_type in ('crypto','stock')),
  backend_id text,
  price numeric,
  note text,
  market_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  title text not null,
  note text not null,
  confidence integer check (confidence between 1 and 10),
  emotion text,
  mistake boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.watchlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  name text,
  asset_type text not null check (asset_type in ('crypto','stock')),
  backend_id text,
  created_at timestamptz not null default now(),
  unique(user_id, symbol, asset_type)
);

create table if not exists public.price_alerts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  target_price numeric not null check (target_price > 0),
  condition text not null check (condition in ('above','below')),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.market_observations enable row level security;
alter table public.market_snapshots enable row level security;
alter table public.journal_entries enable row level security;
alter table public.watchlist_items enable row level security;
alter table public.price_alerts enable row level security;

create policy "own observations" on public.market_observations for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own journal" on public.journal_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own watchlist" on public.watchlist_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own alerts" on public.price_alerts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "read own snapshots" on public.market_snapshots for select using (auth.uid() = user_id);
create policy "create own snapshots" on public.market_snapshots for insert with check (auth.uid() = user_id);

create or replace function public.prevent_snapshot_mutation()
returns trigger language plpgsql as $$
begin
  raise exception 'Market snapshots are immutable';
end;
$$;

create trigger market_snapshots_no_update before update on public.market_snapshots for each row execute function public.prevent_snapshot_mutation();
create trigger market_snapshots_no_delete before delete on public.market_snapshots for each row execute function public.prevent_snapshot_mutation();
