-- Market Memory v2: canonical assets + deduplicated market price time-series

create table if not exists public.market_assets (
  id bigint generated by default as identity primary key,
  symbol text not null,
  name text not null,
  asset_type text not null check (asset_type in ('stock','crypto')),
  backend_id text not null,
  exchange text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(asset_type, backend_id)
);

create index if not exists market_assets_symbol_idx
  on public.market_assets(symbol);

create table if not exists public.market_price_samples (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  price numeric not null check (price > 0),
  currency text not null,
  source text not null,
  sampled_at timestamptz not null default now(),
  bucket_at timestamptz not null,
  unique(asset_id, bucket_at)
);

create index if not exists market_price_samples_asset_time_idx
  on public.market_price_samples(asset_id, sampled_at desc);

create table if not exists public.user_price_marks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  price_sample_id bigint references public.market_price_samples(id) on delete set null,
  context text not null check (context in ('app_foreground','app_background','journal_create','manual')),
  created_at timestamptz not null default now()
);

create index if not exists user_price_marks_user_asset_time_idx
  on public.user_price_marks(user_id, asset_id, created_at desc);

alter table public.market_assets enable row level security;
alter table public.market_price_samples enable row level security;
alter table public.user_price_marks enable row level security;

drop policy if exists "authenticated read market assets" on public.market_assets;
create policy "authenticated read market assets"
  on public.market_assets for select
  to authenticated
  using (true);

drop policy if exists "authenticated read market prices" on public.market_price_samples;
create policy "authenticated read market prices"
  on public.market_price_samples for select
  to authenticated
  using (true);

drop policy if exists "users read own price marks" on public.user_price_marks;
create policy "users read own price marks"
  on public.user_price_marks for select
  to authenticated
  using ((select auth.uid()) = user_id);

alter table public.journal_entries
  add column if not exists asset_id bigint references public.market_assets(id) on delete set null,
  add column if not exists entry_price_sample_id bigint references public.market_price_samples(id) on delete set null;

create index if not exists journal_entries_user_asset_time_idx
  on public.journal_entries(user_id, asset_id, created_at desc);

-- Server-side aggregation keeps years of raw samples off the phone.
create or replace function public.get_market_price_history(
  p_asset_id bigint,
  p_range text default '7d'
)
returns table (
  period_start timestamptz,
  avg_price numeric,
  min_price numeric,
  max_price numeric,
  sample_count bigint
)
language sql
stable
security invoker
set search_path = public
as $$
  with config as (
    select
      case p_range
        when '1d' then now() - interval '1 day'
        when '7d' then now() - interval '7 days'
        when '30d' then now() - interval '30 days'
        when '90d' then now() - interval '90 days'
        when '1y' then now() - interval '1 year'
        else now() - interval '5 years'
      end as since,
      case
        when p_range = '1d' then 'hour'
        when p_range in ('7d','30d','90d') then 'day'
        when p_range = '1y' then 'month'
        else 'year'
      end as grain
  )
  select
    case c.grain
      when 'hour' then date_trunc('hour', s.sampled_at)
      when 'day' then date_trunc('day', s.sampled_at)
      when 'month' then date_trunc('month', s.sampled_at)
      else date_trunc('year', s.sampled_at)
    end as period_start,
    avg(s.price) as avg_price,
    min(s.price) as min_price,
    max(s.price) as max_price,
    count(*) as sample_count
  from public.market_price_samples s
  cross join config c
  where s.asset_id = p_asset_id
    and s.sampled_at >= c.since
  group by 1
  order by 1;
$$;
