-- Market Memory v2: canonical assets + deduplicated market price time-series

create table if not exists public.market_assets (
  id bigint generated by default as identity primary key,
  symbol text not null,
  name text not null,
  asset_type text not null check (asset_type in ('stock','crypto')),
  backend_id text not null,
  exchange text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(asset_type, backend_id)
);

create index if not exists market_assets_symbol_idx
  on public.market_assets(symbol);

create table if not exists public.market_price_samples (
  id bigint generated by default as identity primary key,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  price numeric not null check (price > 0),
  currency text not null,
  source text not null,
  sampled_at timestamptz not null default now(),
  bucket_at timestamptz not null,
  unique(asset_id, bucket_at)
);

create index if not exists market_price_samples_asset_time_idx
  on public.market_price_samples(asset_id, sampled_at desc);

-- Records why a user caused/consumed a sample without duplicating the market price itself.
create table if not exists public.user_price_marks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  asset_id bigint not null references public.market_assets(id) on delete cascade,
  price_sample_id bigint references public.market_price_samples(id) on delete set null,
  context text not null check (context in ('app_foreground','app_background','journal_create','manual')),
  created_at timestamptz not null default now()
);

create index if not exists user_price_marks_user_asset_time_idx
  on public.user_price_marks(user_id, asset_id, created_at desc);

alter table public.market_assets enable row level security;
alter table public.market_price_samples enable row level security;
alter table public.user_price_marks enable row level security;

-- Canonical market data is readable by authenticated users. Writes go through backend service-role only.
drop policy if exists "authenticated read market assets" on public.market_assets;
create policy "authenticated read market assets"
  on public.market_assets for select
  to authenticated
  using (true);

drop policy if exists "authenticated read market prices" on public.market_price_samples;
create policy "authenticated read market prices"
  on public.market_price_samples for select
  to authenticated
  using (true);

drop policy if exists "users read own price marks" on public.user_price_marks;
create policy "users read own price marks"
  on public.user_price_marks for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Journal rows gain optional canonical asset/sample links while old symbol-based rows remain valid.
alter table public.journal_entries
  add column if not exists asset_id bigint references public.market_assets(id) on delete set null,
  add column if not exists entry_price_sample_id bigint references public.market_price_samples(id) on delete set null;

create index if not exists journal_entries_user_asset_time_idx
  on public.journal_entries(user_id, asset_id, created_at desc);
