create table if not exists public.ai_reflection_audits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  model text not null,
  source_entry_ids bigint[] not null default '{}',
  question_fingerprint text not null,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  latency_ms integer not null check (latency_ms >= 0),
  succeeded boolean not null default true,
  error_code text,
  created_at timestamptz not null default now()
);

alter table public.ai_reflection_audits enable row level security;

create policy "Users insert their AI audits"
on public.ai_reflection_audits for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users read their AI audits"
on public.ai_reflection_audits for select to authenticated
using ((select auth.uid()) = user_id);

grant select, insert on public.ai_reflection_audits to authenticated;
grant usage, select on sequence public.ai_reflection_audits_id_seq to authenticated;

create index if not exists ai_reflection_audits_user_created_idx
on public.ai_reflection_audits (user_id, created_at desc);
