import { ReviewActions } from './ReviewActions';
import { localDay } from './reviewDates';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { apiRequest } from '../../services/api';
import { theme } from '../../shared/theme/tokens';
import { EmptyState, MemoryCard, type MemoryCardData, Page, PageIntro, PrimaryAction, SectionHeading, Timeline, formatDate, formatPrice } from '../../shared/ui/NotebookUI';

type Entry={id:number;symbol:string;title:string;note:string;confidence:number|null;expectation?:'bullish'|'bearish'|'neutral'|null;created_at:string;asset_id?:number|null;entry_price_sample_id?:number|null;entry_type?:'observation'|'decision';decision_action?:string|null;invalidation?:string|null;review_due_on?:string|null;lesson?:string|null;reviewed_at?:string|null;review_outcome?:'yes'|'partially'|'no'|null};
type HistoryPoint={period_start:string;avg_price:number;min_price:number;max_price:number;sample_count:number};
type PriceSample={price:number;currency:string;sampled_at:string};
type Review={latest_price?:PriceSample|null;entry:Entry;entry_price?:PriceSample|null;range:string;history:HistoryPoint[]};
type JournalView='all'|'due'|'reviewed';type Range='7d'|'30d'|'90d'|'1y'|'5y';
const toCard=(entry:Entry,review?:Review|null):MemoryCardData=>({id:entry.id,symbol:entry.symbol,title:entry.title,thought:entry.note,recordedAt:entry.created_at,expectation:entry.expectation,reviewDueOn:entry.review_due_on,reviewedAt:entry.reviewed_at,lesson:entry.lesson,confidence:entry.confidence,priceThen:review?.entry.id===entry.id?review.entry_price?.price:null,priceNow:review?.entry.id===entry.id?review.latest_price?.price:null,currency:review?.entry_price?.currency});

export function JournalScreen(){
  const params=useLocalSearchParams<{entry?:string}>();const [view,setView]=useState<JournalView>('all');const [entries,setEntries]=useState<Entry[]>([]);const [loading,setLoading]=useState(false);const [message,setMessage]=useState('');const [review,setReview]=useState<Review|null>(null);const [reviewLoading,setReviewLoading]=useState(false);const [range,setRange]=useState<Range>('30d');const loadSeq=useRef(0);const reviewSeq=useRef(0);
  const load=useCallback(async()=>{const seq=++loadSeq.current;setLoading(true);setMessage('');try{const rows=await apiRequest<Entry[]>(`/api/journal?view=${view}&as_of=${localDay()}&limit=100`);if(seq===loadSeq.current)setEntries(rows);}catch(e){if(seq===loadSeq.current){setEntries([]);setMessage(e instanceof Error?e.message:'Unable to load your memories.');}}finally{if(seq===loadSeq.current)setLoading(false);}},[view]);
  const openReview=useCallback(async(entry:Entry,nextRange:Range='30d')=>{const seq=++reviewSeq.current;setReviewLoading(true);setMessage('');try{const next=await apiRequest<Review>(`/api/journal/${entry.id}/review?range=${nextRange}`);if(seq===reviewSeq.current){setReview(next);setRange(nextRange);}}catch(e){if(seq===reviewSeq.current)setMessage(e instanceof Error?e.message:'Unable to open this memory.');}finally{if(seq===reviewSeq.current)setReviewLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();const id=Number(params.entry);if(Number.isSafeInteger(id)&&id>0){const existing=entries.find(item=>item.id===id);if(existing)void openReview(existing);else apiRequest<Review>(`/api/journal/${id}/review?range=30d`).then(setReview).catch(()=>{});}return()=>{loadSeq.current++;reviewSeq.current++;};},[load,openReview,params.entry]));
  const summary=useMemo(()=>{const original=review?.entry_price;const latest=review?.latest_price;if(!original||!latest||original.currency!==latest.currency||original.price<=0)return null;return{entry:original.price,last:latest.price,change:((latest.price-original.price)/original.price)*100,currency:original.currency};},[review]);
  const timeline=useMemo<Array<{date:string;label:string;body:string;tone?:'accent'|'review'|'muted'}>>(()=>{if(!review)return[];const events:Array<{date:string;label:string;body:string;tone?:'accent'|'review'|'muted'}>=[{date:review.entry.created_at,label:'Original thought',body:review.entry.note,tone:'accent'},...review.history.slice(-4).map(point=>({date:point.period_start,label:'Recorded market context',body:`Average ${formatPrice(point.avg_price,review.entry_price?.currency||'INR')} · ${point.sample_count} ${point.sample_count===1?'sample':'samples'}`,tone:'muted' as const}))];if(review.entry.reviewed_at)events.push({date:review.entry.reviewed_at,label:'Reflection',body:review.entry.lesson||'Review completed.',tone:'review'});else if(review.entry.review_due_on)events.push({date:review.entry.review_due_on,label:'Review date',body:'Return with fresh evidence.',tone:'review'});return events;},[review]);
  return <ScrollView style={s.screen} contentContainerStyle={s.scroll}><Page wide>
    <PageIntro eyebrow="Review" title="Your thinking, preserved." subtitle="Return to it with fresh evidence." action={<PrimaryAction label="＋ Record thought" href="/(tabs)/market"/>}/>
    <View style={s.tabs}>{(['all','due','reviewed'] as JournalView[]).map(item=><Pressable key={item} accessibilityRole="button" accessibilityState={{selected:view===item}} onPress={()=>{setView(item);setReview(null);}} style={[s.tab,view===item&&s.tabActive]}><Text style={[s.tabText,view===item&&s.tabTextActive]}>{item==='all'?'All':item==='due'?'Reviews due':'Reviewed'}</Text></Pressable>)}</View>
    {message?<Text accessibilityRole="alert" style={s.message}>{message}</Text>:null}
    {reviewLoading?<ActivityIndicator color={theme.colors.accent} style={s.loader}/>:null}
    {review?<View style={s.detail}>
      <View style={s.detailTop}><Pressable onPress={()=>setReview(null)} style={s.back}><Text style={s.backText}>← All memories</Text></Pressable><Text style={s.detailStatus}>{review.entry.reviewed_at?'✓ Reviewed':review.entry.review_due_on&&review.entry.review_due_on<=localDay()?'↻ Review due':'● Active'}</Text></View>
      <Text style={s.detailSymbol}>{review.entry.symbol}</Text><Text style={s.recorded}>Recorded {formatDate(review.entry.created_at)}</Text>
      <Text style={s.blockLabel}>Your thought</Text><Text style={s.original}>“{review.entry.note}”</Text>
      {review.entry.invalidation?<><Text style={s.blockLabel}>Evidence that would change your mind</Text><Text style={s.supporting}>{review.entry.invalidation}</Text></>:null}
      <View style={s.divider}/>
      <Text style={s.blockLabel}>What happened since</Text>
      {summary?<View style={s.outcome}><View><Text style={s.outcomeValue}>{formatPrice(summary.entry,summary.currency)} → {formatPrice(summary.last,summary.currency)}</Text><Text style={s.supporting}>Recorded market samples</Text></View><Text style={[s.change,{color:summary.change>=0?theme.colors.positive:theme.colors.negative}]}>{summary.change>=0?'+':''}{summary.change.toFixed(1)}%</Text></View>:<Text style={s.supporting}>A comparison will appear after a later price is recorded. Missing prices are never estimated.</Text>}
      <View style={s.ranges}>{(['7d','30d','90d','1y','5y'] as Range[]).map(item=><Pressable key={item} onPress={()=>void openReview(review.entry,item)} style={[s.range,item===range&&s.rangeActive]}><Text style={[s.rangeText,item===range&&s.rangeTextActive]}>{item.toUpperCase()}</Text></Pressable>)}</View>
      <SectionHeading title={`${review.entry.symbol} memory timeline`} detail="Thought → context → reflection"/><Timeline events={timeline}/>
      <ReviewActions key={review.entry.id} entry={review.entry} onSaved={updated=>{setReview(current=>current&&current.entry.id===updated.id?{...current,entry:{...current.entry,...updated}}:current);void load();}}/>
    </View>:<>
      <SectionHeading title={view==='due'?'Memories waiting for you':view==='reviewed'?'Completed reflections':'Memory notebook'} detail={loading?'Refreshing…':`${entries.length} ${entries.length===1?'memory':'memories'}`}/>
      {!loading&&!entries.length?<EmptyState title={view==='due'?'Nothing to review.':view==='reviewed'?'No completed reviews yet.':'No memories yet.'} body={view==='due'?'Your next review will appear here when a memory reaches its review date.':view==='reviewed'?'Complete a review to preserve what you learned.':'Your notebook starts with one thought. Choose an asset and record what you expect.'} action={view==='all'?'Record your first thought':undefined} href={view==='all'?'/\(tabs\)/market' as never:undefined}/>:entries.map(entry=><MemoryCard key={entry.id} item={toCard(entry)} onPress={()=>void openReview(entry)}/>)}
    </>}
  </Page></ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:theme.colors.bg},scroll:{minHeight:'100%'},tabs:{flexDirection:'row',borderBottomWidth:1,borderBottomColor:theme.colors.borderSubtle,marginBottom:theme.space.md},tab:{minHeight:44,justifyContent:'center',paddingHorizontal:theme.space.md,borderBottomWidth:2,borderBottomColor:'transparent'},tabActive:{borderBottomColor:theme.colors.accent},tabText:{...theme.type.caption,color:theme.colors.textMuted},tabTextActive:{color:theme.colors.text},message:{...theme.type.caption,color:theme.colors.textSecondary,marginVertical:theme.space.sm},loader:{marginVertical:theme.space.lg},detail:{maxWidth:820,width:'100%',alignSelf:'center'},detailTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:theme.space.md},back:{minHeight:44,justifyContent:'center'},backText:{...theme.type.caption,color:theme.colors.accent},detailStatus:{...theme.type.metadata,color:theme.colors.review},detailSymbol:{fontSize:28,lineHeight:36,fontWeight:'600',color:theme.colors.text,marginTop:theme.space.lg},recorded:{...theme.type.metadata,color:theme.colors.textDim},blockLabel:{...theme.type.metadata,color:theme.colors.textDim,textTransform:'uppercase',marginTop:theme.space.xl,marginBottom:theme.space.xs},original:{fontSize:23,lineHeight:34,fontWeight:'400',color:theme.colors.text,maxWidth:720},supporting:{...theme.type.body,color:theme.colors.textMuted},divider:{height:1,backgroundColor:theme.colors.borderSubtle,marginTop:theme.space.xl},outcome:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',alignItems:'flex-end',gap:theme.space.md},outcomeValue:{...theme.type.marketValue,color:theme.colors.text},change:{fontSize:22,fontWeight:'600'},ranges:{flexDirection:'row',flexWrap:'wrap',gap:theme.space.xs,marginTop:theme.space.md},range:{minHeight:38,justifyContent:'center',paddingHorizontal:theme.space.sm,borderRadius:theme.radius.pill,borderWidth:1,borderColor:theme.colors.borderSubtle},rangeActive:{backgroundColor:theme.colors.accentSoft,borderColor:theme.colors.accent},rangeText:{...theme.type.metadata,color:theme.colors.textDim},rangeTextActive:{color:theme.colors.text}});
